fixtures:
  repositories:
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
  symlinks:
    aem: "#{source_dir}"
