inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.0

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

# Disabled undesired features
Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '||'
